### ISSUE TITLE
Aliasing Scoop causes Find-ScoopApp to fail

### ISSUE THREAD

**Issue by riotrah** [ThomasNieto/Scoop#9]
Hi!

I applaud your efforts with AnyPackage. I notice it depends on this Module, and I'm interested in using both.

Anyways, I tried Find-ScoopApp, but it always errors out with:

```pwsh
$ Find-ScoopApp Ticktick

Select-Object: Property "Path" cannot be found.
Join-Path: Cannot bind argument to parameter 'Path' because it is null.
```

If this works in your env then I can provide any env details of mine you might need.

**Comment by ThomasNieto** [comment]
@riotrah can you please run the following command to see if the Scoop command is found? I don't think `TickTick` is a valid program but I was able to properly test with `7zip`.

```powershell
Get-Command -Name Scoop
```

**Comment by riotrah** [comment]
Ah, upon looking at the `.Definition` for scoop, I remember that I'd aliased `scoop` to an fn in my profile that does a few things, among which using [scoop-search-multisource](https://github.com/plicit/scoop-search-multisource) if `scoop search *` is ran, otherwise reverting to vanilla scoop.

I know that my redefining what `scoop` refers to in my setup is outside the scope of concern for your tool, but if it were possible to alter references to `scoop` in this proj to `scoop.exe`, that would likely work uniformly 🤷🏽.

Unless, I suppose, someone _wanted_ to do what I'd done, but make less output-affecting changes, in which case keeping your code as-is would likely be preferable as an escape hatch of some sort.

I wonder if I can redefine `scoop` just for the duration of invoking `Find-ScoopApp`... Will try that.

Sorry for the noise!

**Comment by riotrah** [comment]
I don't know pwsh very well, but trying something like `new-alias scoop scoop.exe && Find-ScoopApp 7zip` doesn't work. Happy to stop bothering you on this tho, I suppose I could rename my aliases

**Comment by ThomasNieto** [comment]
The module finds the `Scoop.ps1` to find the directory it resides in to find the install directory so it can do its own finding packages since Scoop is slow.

To fix the issue of you overwriting Scoop with your own function I'd need to update the module to do this:

```powershell
Get-Command -Name Scoop -CommandType ExternalScript
```

@riotrah can you please run this command and paste the results here?

**Comment by ThomasNieto** [comment]
@riotrah v0.1.3 includes a fix for this issue. Give it a shot and let me know if you still run into the issue.
